# Generated by Django 5.0.6 on 2026-09-13 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('email_sent', models.BooleanField(default=False)),
                ('emailed_to', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField(help_text='First day of the rent month this payment covers.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_applied', models.DecimalField(decimal_places=2, default=0, help_text="Portion of this month's rent settled from the security deposit.", max_digits=12)),
                ('topup_amount', models.DecimalField(decimal_places=2, default=0, help_text='Rent-increase portion that had to be paid in cash/bank/bkash on top of the deposit.', max_digits=12)),
                ('payment_date', models.DateField()),
                ('due_date', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('bkash', 'Bkash'), ('deposit', 'Security Deposit')], max_length=10)),
                ('topup_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('bkash', 'Bkash'), ('deposit', 'Security Deposit')], help_text='Method used for the rent-increase top-up when paying from deposit.', max_length=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='paid', max_length=10)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='payments/screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.invoice')),
                ('occupancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='properties.occupancy')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'unique_together': {('occupancy', 'period_month')},
            },
        ),
    ]
