# Generated by Django 5.0.6 on 2026-09-13 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Building No')),
                ('name', models.CharField(max_length=120, verbose_name='Building Name')),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='buildings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('nid', models.CharField(blank=True, max_length=40, verbose_name='NID No')),
                ('occupant_id', models.CharField(help_text='Internal reference, e.g. OCC-0001', max_length=20, unique=True, verbose_name='Occupant ID')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Level No')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='properties.building')),
            ],
            options={
                'ordering': ['building', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Flat No')),
                ('unit_type', models.CharField(choices=[('flat', 'Flat'), ('shop', 'Shop'), ('cottage', 'Cottage')], default='flat', max_length=10)),
                ('size_sqft', models.PositiveIntegerField(default=0, verbose_name='Size (sqft)')),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('amenities', models.TextField(blank=True, help_text='Comma separated amenities')),
                ('base_rent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='properties.level')),
            ],
            options={
                'ordering': ['level__building__number', 'level__number', 'number'],
                'unique_together': {('level', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Occupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Rent agreed at the start of the tenancy. Later increases are recorded as rent revisions.', max_digits=12, verbose_name='Initial monthly rent')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, help_text="Deposit taken at move-in. Can be applied to final months' rent when the occupant leaves.", max_digits=12)),
                ('deposit_balance', models.DecimalField(decimal_places=2, default=0, help_text='Remaining unused deposit.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notice_given', models.BooleanField(default=False, help_text='Occupant has given notice to leave — unlocks payment from the security deposit.')),
                ('agreement_reference', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='properties.flat')),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='properties.occupant')),
            ],
            options={
                'verbose_name_plural': 'Occupancies',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('nid', 'NID'), ('id', 'ID Card'), ('agreement', 'Agreement'), ('legal', 'Legal Proof'), ('other', 'Other')], default='other', max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='documents/occupants/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.occupant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='First month the new rent applies to.')),
                ('new_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occupancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='properties.occupancy')),
            ],
            options={
                'ordering': ['effective_from'],
            },
        ),
    ]
